set.seed(42)
df <- read.csv("reconstructed_raw_data_50.csv")
cat("=== 01 DATA IMPORT VALIDATION ===\n")
cat("Dimensions: ", nrow(df), "x", ncol(df), "\n")
str(df)
cat("Missing values:\n")
print(colSums(is.na(df)))
stopifnot(nrow(df) == 50)
cat("Data validation successful.\n")
